In [1]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

### 在计算y 关于x 的梯度之前，我们需要一个地方来存储梯度

In [2]:
x.requires_grad_(True)
x.grad

### 现在我们来计算y。

In [4]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

### 通过调用反向传播函数来自动计算y关于x每个分量的梯度

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad==4*x

tensor([True, True, True, True])

### 现在计算x的另一个函数

In [8]:
#默认情况下，pytorch会累积梯度，需要清除之前的值
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [1]:
print("tes")

tes


In [1]:
print("dfjkd")

dfjkd
