In [1]:
%matplotlib inline 
import random 
import torch
from d2l import torch as d2l

In [2]:
def synthetic_data(w,b,num_examples):
    x=torch.normal(0,1,(num_examples,len(w)))
    y=torch.matmul(x,w)+b
    y+=torch.normal(0,0.01,y.shape)
    return x,y.reshape((-1,1))
true_w=torch.tensor([2,-3.4])
true_b=4.2
features,labels=synthetic_data(true_w,true_b,10)

## 写下面的函数前的测试

In [12]:
num_examples=len(features)
print(num_examples)

10


In [13]:
indices=list(range(num_examples))
print(indices)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
random.shuffle(indices)
print(indices)

[1, 6, 5, 7, 4, 8, 0, 9, 3, 2]


In [20]:
indices[0:5]

[1, 6, 5, 7, 4]

In [21]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [29]:
print(features)
num_examples=len(features)
indices=list(range(num_examples))
random.shuffle(indices)
for i in range(0,num_examples,2):
        batch_indices=torch.tensor(
            indices[i:min(i+2,num_examples)])
        print(batch_indices)
        print(features[batch_indices],labels[batch_indices])
        print('\n')

tensor([[-1.1815, -1.4367],
        [-0.5424,  0.7147],
        [ 1.8042,  0.9787],
        [-0.4213,  1.2445],
        [-1.6473,  0.3432],
        [ 0.4952, -0.4321],
        [ 1.0479, -0.1214],
        [ 1.3426, -0.8107],
        [-2.7168, -0.4283],
        [ 0.5945,  0.1303]])
tensor([3, 9])
tensor([[-0.4213,  1.2445],
        [ 0.5945,  0.1303]]) tensor([[-0.8999],
        [ 4.9389]])


tensor([8, 6])
tensor([[-2.7168, -0.4283],
        [ 1.0479, -0.1214]]) tensor([[0.2286],
        [6.7029]])


tensor([1, 5])
tensor([[-0.5424,  0.7147],
        [ 0.4952, -0.4321]]) tensor([[0.6835],
        [6.6463]])


tensor([4, 0])
tensor([[-1.6473,  0.3432],
        [-1.1815, -1.4367]]) tensor([[-0.2710],
        [ 6.7251]])


tensor([7, 2])
tensor([[ 1.3426, -0.8107],
        [ 1.8042,  0.9787]]) tensor([[9.6474],
        [4.4766]])




## 定义一个data_iter函数，该函数接受批量大小，特征矩阵和标签向量作为输入，生成大小为batch——size的小批量

In [31]:
def data_iter(batch_size,features,labels):
    num_examples=len(features)
    indices=list(range(num_examples))
    random.shuffle(indices)
    for i in range(0,num_examples,batch_size):
        batch_indices=torch.tensor(
            indices[i:min(i+batch_size,num_examples)])
        yield features[batch_indices],labels[batch_indices]
batch_size=2
data_iter(batch_size,features,labels)
for X,y in data_iter(batch_size,features,labels):
    print(X,'\n',y)
    break

tensor([[ 1.0479, -0.1214],
        [ 0.4952, -0.4321]]) 
 tensor([[6.7029],
        [6.6463]])


## 定义初始化模型参数

In [32]:
w=torch.normal(0,0.01,(2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)


## 定义模型

In [33]:
def linreg(x,w,b):
    """线性回归模型"""
    return torch.matul(x,w)+b