# 2 预备知识 

In [1]:
import torch # 如果pytorch安装成功即可导入



In [2]:
x=torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

输出张量中元素的个数

In [5]:
x.numel()

12

In [6]:
X=x.reshape(3,4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros(3,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,5,6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [9]:
torch.randn(3,4)

tensor([[-0.8233,  1.2048, -0.5254,  0.1686],
        [ 1.2559,  0.1396, -0.4290,  0.5126],
        [-0.1724, -0.5692,  0.3649, -0.6638]])

In [10]:
torch.tensor([[1,2,3],[2,3,4],[5,6,7]])

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

In [12]:
x=torch.tensor([1.9,3,5,6])
y=torch.tensor([2,4,5,3])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.9000,  7.0000, 10.0000,  9.0000]),
 tensor([-0.1000, -1.0000,  0.0000,  3.0000]),
 tensor([ 3.8000, 12.0000, 25.0000, 18.0000]),
 tensor([0.9500, 0.7500, 1.0000, 2.0000]),
 tensor([   3.6100,   81.0000, 3125.0000,  216.0000]))

In [15]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X,Y
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [20]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [25]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[1,1]=0
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  0.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
X[1:3,:]

tensor([[ 4.,  0.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  0.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [32]:
before=id(Y)
print(before)
Y=Y+X
id(Y)==before

1734366215920


False

In [33]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 1734361437424
id(Z): 1734361437424


In [34]:
before=id(X)
X+=Y
id(X)==before

True

### 2.16 转换为其他Python对象

In [36]:
a=X.numpy()
b=torch.tensor(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)

## 2.2 数据预处理

### 2.2.1读取数据集 

In [6]:
import os 

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRoos,Alley,prince\n')#列明
    f.write('NA,pave,12555\n')
    f.write('2,NA,132323\n')
    f.write('4,NA,dfadf\n')
    f.write('5,NA,dfadfa\n')

In [7]:
import pandas as pd 
data=pd.read_csv(data_file)
print(data)

   NumRoos Alley  prince
0      NaN  pave   12555
1      2.0   NaN  132323
2      4.0   NaN   dfadf
3      5.0   NaN  dfadfa


### 2.2.2 处理缺失值

In [15]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
#inputs
inputs=inputs.fillna(inputs.mean())
print(inputs)

TypeError: can only concatenate str (not "int") to str

TypeError: can only concatenate str (not "int") to str